// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdmedkzrioodkzkoogki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkbWVka3pyaW9vZGt6a29vZ2tpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MjQxNDQsImV4cCI6MjA3MjIwMDE0NH0.zonbr_E4eJK1pn2epC4eUUNGkgdKZ96SAO7GlaHUK9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});